name = "Rmath"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.7.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rmath_jll = "f50d1b31-88e8-58de-be2c-1cc44531875f"

[compat]
Rmath_jll = "0.3, 0.4"
julia = "1.3"

[extras]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Statistics", "Test"]
